#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: install-git-clone
      taskSpec:
        steps:
          - name: install-git-clone
            image: bitnami/kubectl:latest  # Ensure the image has the `tkn` or `kubectl` binary
            script: |
              tkn hub install task git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      runAfter:
        - init

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - install-git-clone

    - name: install-flake8
      taskSpec:
        steps:
          - name: install-flake8
            image: bitnami/kubectl:latest
            script: |
              if ! tkn hub get task flake8; then
                tkn hub install task flake8
              else
                echo "flake8 task is already installed."
              fi
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - clone


    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: flake8
      params:
      - name: image
        value: python:3.9-slim
      - name: args
        value: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics", "--exit-zero"]
      runAfter:
        - clone
